version: '3.7'

services:
  glpi:
    build: .
    container_name: glpi
    ports:
      - "8080:80"
    volumes:
      - ./glpi:/var/www/html/glpi
    environment:
      MYSQL_HOST: db
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipassword
      MYSQL_DATABASE: glpi
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: glpi-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
